### ISSUE TITLE
Support empty and missing user agent

### ISSUE THREAD

**Issue by charlax** [ariesjia/jest-useragent-mock#5]
What do you think about supporting a missing and empty user agent?

The current `||` in the implementation prevents doing `mockUserAgent(null)`.

**Comment by ariesjia** [comment]
Good suggestion, may add it later.
I haven't considered this scenario before

**Comment by ariesjia** [comment]
Thank you so much for this suggestion,  I have completed this enhancement and  version 0.1.0  plubished.
Here is test case
https://github.com/ariesjia/jest-useragent-mock/blob/adb70a72da509b18d2472c3ce84f98e74a2b0470/src/index.test.js#L19-L27

**Comment by charlax** [comment]
That's amazing, thanks so much!

I'm getting this with no argument:

```
node_modules/jest-useragent-mock/index.d.ts:1:39
    1 export declare function mockUserAgent(userAgent: string): void;
                                            ~~~~~~~~~~~~~~~~~
    An argument for 'userAgent' was not provided.
```

**Comment by ariesjia** [comment]
Sorry,  forgot to update the typing file.  
I have updated and published 😊
